apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oem-services-hpa
  namespace: oem-seller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oemproduct-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70